version: "3"
services:
    web:
        build:
           context: .
           dockerfile: src/Questor.Web/Dockerfile
        environment:
            DB_PASS: "${DB_PASS}"           
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        environment:
            SA_PASSWORD: "${DB_PASS}"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
